-- ============================================================================
-- Delivery 3: Analytics Visualization System - UPC Database Schema
-- ============================================================================
-- Created: 2026-01-04
-- Purpose: Store gameplay analytics data for Unity 3D Game Kit Lite
-- Schema: test (UPC Database)
-- Table Prefix: delivery3_ (to avoid conflicts)
-- ============================================================================

USE test;

-- ============================================================================
-- Table: delivery3_sessions
-- Purpose: Tracks gameplay sessions
-- ============================================================================
CREATE TABLE IF NOT EXISTS delivery3_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) UNIQUE NOT NULL COMMENT 'UUID generated by Unity',
    start_time DATETIME NOT NULL COMMENT 'Session start timestamp',
    end_time DATETIME NULL COMMENT 'Session end timestamp (null if ongoing)',
    duration_seconds INT NULL COMMENT 'Total session duration',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_session_id (session_id),
    INDEX idx_start_time (start_time)
) ENGINE=InnoDB COMMENT='Delivery 3 gameplay sessions';

-- ============================================================================
-- Table: delivery3_player_positions
-- Purpose: High-frequency spatial data tracking player movement
-- ============================================================================
CREATE TABLE IF NOT EXISTS delivery3_player_positions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    position_x FLOAT NOT NULL COMMENT 'World X coordinate',
    position_y FLOAT NOT NULL COMMENT 'World Y coordinate',
    position_z FLOAT NOT NULL COMMENT 'World Z coordinate',
    speed FLOAT NULL COMMENT 'Player velocity magnitude',
    timestamp FLOAT NOT NULL COMMENT 'Seconds since session start',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (session_id) REFERENCES delivery3_sessions(session_id) ON DELETE CASCADE,
    INDEX idx_session (session_id),
    INDEX idx_timestamp (session_id, timestamp)
) ENGINE=InnoDB COMMENT='Player position samples (2 Hz default)';

-- ============================================================================
-- Table: delivery3_death_events
-- Purpose: Player and enemy death tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS delivery3_death_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    entity_type VARCHAR(50) NOT NULL COMMENT 'Player, Chomper, Spitter, Grenadier, etc.',
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    position_z FLOAT NOT NULL,
    cause VARCHAR(100) NULL COMMENT 'Damage source (e.g., "Chomper", "Fall", "Spitter Projectile")',
    timestamp FLOAT NOT NULL COMMENT 'Seconds since session start',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (session_id) REFERENCES delivery3_sessions(session_id) ON DELETE CASCADE,
    INDEX idx_session (session_id),
    INDEX idx_entity_type (entity_type),
    INDEX idx_timestamp (session_id, timestamp)
) ENGINE=InnoDB COMMENT='Death events for players and enemies';

-- ============================================================================
-- Table: delivery3_pickup_events
-- Purpose: Item collection tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS delivery3_pickup_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    item_name VARCHAR(100) NOT NULL COMMENT 'Key, Health, Staff, etc.',
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    position_z FLOAT NOT NULL,
    timestamp FLOAT NOT NULL COMMENT 'Seconds since session start',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (session_id) REFERENCES delivery3_sessions(session_id) ON DELETE CASCADE,
    INDEX idx_session (session_id),
    INDEX idx_item (item_name),
    INDEX idx_timestamp (session_id, timestamp)
) ENGINE=InnoDB COMMENT='Item pickup events';

-- ============================================================================
-- Table: delivery3_combat_events
-- Purpose: Damage dealt tracking
-- ============================================================================
CREATE TABLE IF NOT EXISTS delivery3_combat_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    attacker VARCHAR(50) NOT NULL COMMENT 'Player or enemy type',
    target VARCHAR(50) NOT NULL COMMENT 'Player or enemy type',
    damage_amount FLOAT NOT NULL,
    position_x FLOAT NOT NULL,
    position_y FLOAT NOT NULL,
    position_z FLOAT NOT NULL,
    timestamp FLOAT NOT NULL COMMENT 'Seconds since session start',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (session_id) REFERENCES delivery3_sessions(session_id) ON DELETE CASCADE,
    INDEX idx_session (session_id),
    INDEX idx_attacker (attacker),
    INDEX idx_timestamp (session_id, timestamp)
) ENGINE=InnoDB COMMENT='Combat damage events';

-- ============================================================================
-- Verification Queries
-- ============================================================================
-- Run these after schema creation to verify structure:

-- SHOW TABLES LIKE 'delivery3_%';
-- DESCRIBE delivery3_sessions;
-- DESCRIBE delivery3_player_positions;
-- DESCRIBE delivery3_death_events;
-- DESCRIBE delivery3_pickup_events;
-- DESCRIBE delivery3_combat_events;

-- ============================================================================
-- Sample Test Insert
-- ============================================================================
-- Uncomment to test:
-- INSERT INTO delivery3_sessions (session_id, start_time)
-- VALUES ('test-session-001', NOW());
--
-- SELECT * FROM delivery3_sessions;
